export const RegisterStyle = {
  ButtonStyle: {
    display: "flex",
    width: "300px",
    justifyContent: "space-evenly",
    fontSize: "13px",
  },
  inputStyle: {
    backgroundColor: "#F3F4F6",
    border: "1px solid grey",
    padding: "10px",
    borderRadius: "5px",
    width: "25vw",
    color: "black",
  },
  SignUpSubmitButton: {
    width: "25vw",
    backgroundColor: "#0166FF",
    padding: "10px",
    border: "none",
    borderRadius: "10px",
    color: "white",
  },
  SignUpInputDiv: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "30px",
    width: "25vw",
  },
  StepperDivStyle: {
    backgroundColor: "white",
    width: "100vw",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
};
